language: python
matrix:
  include:
    - os: linux
      python: 2.7
      env: CONDA_ENV=python2
    - os: linux
      python: 3.7
      env: CONDA_ENV=python3
    - os: osx
      language: generic
      env: CONDA_ENV=python2
    - os: osx
      language: generic
      env: CONDA_ENV=python3
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
    fi
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      if [[ "$CONDA_ENV" == "python2" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    else
      if [[ "$CONDA_ENV" == "python2" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda update -y -q conda
  - conda info -a
  - conda install -y -q conda-build anaconda-client
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda config --add channels plotly
  - conda config --add channels programfan
  - conda config --set conda_build.skip_existing true
  - conda config --set conda_build.no_verify true

script:
  - ./build.sh
