{% set name = "compiledb" %}
{% set version = "0.10.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 06bb47dd1fa04de3a12720379ff382d40441074476db7c16a27e2ad79b7e966e

build:
  number: 0
  noarch: python
  entry_points:
    - compiledb=compiledb.cli:cli
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - bashlex
    - click
    - pip
    - python
    - shutilwhich
  run:
    - bashlex
    - click
    - python
    - shutilwhich

test:
  imports:
    - compiledb
    - compiledb.commands
  commands:
    - compiledb --help

about:
  home: "https://github.com/nickdiego/compiledb"
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  summary: "Tool for generating Clang JSON Compilation Database files for make-based build systems."

extra:
  recipe-maintainers:
    - programfan
