{% set name = "compiledb" %}
{% set version = "0.9.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ded1e9f69c20b62ddc761900bbd48faa9da21b77e4301376515ee1f7ed362a06

build:
  number: 0
  noarch: python
  entry_points:
    - compiledb=compiledb.cli:cli
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - bashlex
    - click
    - python

test:
  imports:
    - compiledb
    - compiledb.commands
  commands:
    - compiledb --help

about:
  home: https://github.com/nickdiego/compiledb-generator
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: 
  summary: Tool for generating Clang JSON Compilation Database files for make-based build systems.
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
