{% set version = "0.1.0a4" %}

package:
  name: plotlylab
  version: {{ version }}

source:
  url: https://github.com/plotly/plotlylab/archive/v{{version}}.tar.gz
  sha256: 570844d99886aa74e0e4e658cf6050798a384de7483ad40765f302f0ecde0ff2

build:
  number: 4
  noarch: python
  entry_points:
    - plotly-lab = plotlylab.labapp:main
    - plotly-labextension = plotlylab.labextensionapp:main

requirements:
  build:
    - python
    - pip
    - nodejs
    - jupyterlab
  run:
    - jupyterlab
    - jupyterlab-git 0.9.0
    - jupyterlab-dash 0.1.0a3 # [ py3k ]
    - ipywidgets
    - plotly
    - plotly-orca
    - psutil # required by plotly-orca but not implicitly deped.
    - dash
    - dash-html-components
    - dash-core-components
    - dash-daq
    - dash-table
    - dash-renderer
    - numpy
    - pandas
    - colorlover

about:
  home: https://github.com/plotly/plotlylab
  license: MIT
  license_file: LICENSE
  summary: A modified plotlylab distribution
