{% set version = "0.1.0a4" %}

package:
  name: plotlylab
  version: 2.1.0

source:
  url: https://github.com/plotly/plotlylab/archive/v{{version}}.tar.gz
  sha256: 570844d99886aa74e0e4e658cf6050798a384de7483ad40765f302f0ecde0ff2

build:
  number: 0
  noarch: python
  entry_points:
    - plotly-lab = plotlylab.labapp:main
    - plotly-labextension = plotlylab.labextensionapp:main

requirements:
  build:
    - python
    - pip
    - nodejs
    - jupyterlab >=2.1
  run:
    - jupyterlab >=2.1
    - ipywidgets
    - plotly >=4.6

about:
  home: https://github.com/plotly/plotlylab
  license: MIT
  license_file: LICENSE
  summary: A modified plotlylab distribution
