{% set version = "0.1.0" %}

package:
  name: jupyterlab-extension-pack
  version: {{ version }}

build:
  number: 1
  noarch: python

requirements:
  build:
    - nodejs
    - jupyterlab

about:
  home: https://github.com/programfan/conda-packages
  license: MIT
  summary: A set of jupyterlab extensions
