{% set name = "fprettify" %}
{% set version = "0.3.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b68d8e85ddb49be8e1580f6de4ada4dc65b71e11fea611eecd77f3154868154

build:
  number: 0
  noarch: python
  entry_points:
    - fprettify = fprettify:run
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - fprettify
  commands:
    - fprettify --help

about:
  home: https://github.com/pseewald/fprettify
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: 
  summary: auto-formatter for modern fortran source code
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - programfan
