{% set name = "fprettify" %}
{% set version = "0.3.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/pseewald/fprettify/archive/refs/tags/v{{version}}.zip
  sha256: 1dcd817ecb2cdb13ef10403810f861c79694b29d1ecab142642341c55226c076

build:
  number: 0
  noarch: python
  entry_points:
    - fprettify = fprettify:run
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  commands:
    - fprettify --help

about:
  home: https://github.com/pseewald/fprettify
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  summary: auto-formatter for modern fortran source code

extra:
  recipe-maintainers:
    - programfan
