{% set name = "fprettify" %}
{% set version = "0.3.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a5a8741f9e732ced9f5a326a880f4005501a732578322bba1a541db64e165533

build:
  number: 0
  noarch: python
  entry_points:
    - fprettify = fprettify:run
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  commands:
    - fprettify --help

about:
  home: https://github.com/pseewald/fprettify
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  summary: auto-formatter for modern fortran source code

extra:
  recipe-maintainers:
    - programfan
