{% set name = "cmake-language-server" %}
{% set version = "0.1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/ProgramFan/cmake-language-server/archive/refs/tags/v{{version}}.zip
  sha256: 569b9b97b54b4b0af73e575c7897dcba4002fe13afaba16662c9c70a12c45200

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - pygls >=0.11
    - pyparsing 2.4
    - poetry-core >=1.0
  run:
    - python
    - pygls >=0.11
    - pyparsing 2.4

test:
  commands:
    - cmake-language-server --help

about:
  home: https://github.com/regen100/cmake-language-server
  license: MIT
  summary: language server for cmake

extra:
  recipe-maintainers:
    - programfan
