{% set name = "compdb" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 73471badd01e5e69c816fb3a4e0d014f099c2826ee283df5716cd7b1902b79dd

build:
  number: 0
  noarch: python
  entry_points:
    - compdb=compdb.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  commands:
    - compdb --help

about:
  home: https://github.com/Sarcasm/compdb
  license: MIT
  license_family: MIT
  summary: The compilation database Swiss army knife

extra:
  recipe-maintainers:
    - programfan
