{% set name = "neovim" %}
{% set version = "0.4.3" %}
{% set sha256 = "91a0b5d32204a821bf414690e6b48cf69224d1961d37158c2b383f6a6cf854d2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/neovim/neovim/archive/v{{version}}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 5

requirements:
  build:
    - {{ compiler('c') }}
    - cmake >=3.0
    - git
  run:
    - pynvim

about:
  home: https://neovim.io
  license: MIT
  license_family: MIT
  summary: 'hyperextensible Vim-based text editor'

extra:
  recipe-maintainers:
    - programfan
