{% set name = "fortran-language-server" %}
{% set version = "1.12.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/hansec/fortran-language-server/archive/refs/tags/v{{version}}.zip
  sha256: b349743bae98d810cd48e661e978656e452f7bd3a6a7f344bee5892794c097f3

build:
  number: 0
  noarch: python
  entry_points:
    - fortls = fortls.__init__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - future
    - pip
    - python
  run:
    - future
    - python

test:
  commands:
    - fortls --help

about:
  home: https://github.com/hansec/fortran-language-server
  license: UNKNOWN
  license_family: OTHER
  summary: FORTRAN Language Server for the Language Server Protocol

extra:
  recipe-maintainers:
    - programfan
